apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: dev
spec:
  rules:
  - host: k8training.ibunmasood.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80





        #   sets rules for ingress nginx load balancer