apiVersion: v1
kind: Service
metadata:
    name: securemongo
    labels:
    name: securemongo
spec:
    ports:
    - port: 27017
      targetPort: 27017
    clusterIP: None
    selector:
       role: securemongo
