apiVersion: v1
kind: Service
metadata:
  name: securemongo-0
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: securemongo-0
  ports:
  - protocol: TCP
    port: 27017
    nodePort: 30036
    targetPort: 27017