apiVersion: v1
kind: Service
metadata:
  name: mongo-0
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: mongo-0
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017