apiVersion: v1
kind: Service
metadata:
    name: kafka-svc
    labels:
    app: kafka
spec:
    ports:
    - name: server
      port: 9093
      targetPort: 9093
    clusterIP: None
    selector:
    app: kafka