apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: dev
spec:
  rules:
  - host: www.k8training.ibumasood.com
    http:
      path: /
      - backend:
          serviceName: hello-service
          servicePort: 80