apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: dev
spec:
  rules:
  - host: k8training.ibumasood.com
    http:
      paths:
      - path: /
        backend:
            serviceName: hello-service
            servicePort: 80