apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
    department: servers
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
      run: nginx

      #exposes hello world deployment