apiVersion: v1
kind: Service
metadata:
    name: kafka-svc
    labels:
    name: kafka
spec:
    ports:
    - name: server
      port: 9093
      nodePort: 30032
      targetPort: 9093
    type: NodePort
    selector:
      app: kafka