---
apiVersion: v1
kind: Service
metadata:
    name: mongo
    labels:
    name: mongo
spec:
    ports:
    - name : mongoport
      port: 27017
      nodePort: 30011
    # clusterIP: None
    type: NodePort
    selector:
      role: mongo
---