---
apiVersion: v1
kind: Service
metadata:
    name: mongo
    labels:
    name: mongo
spec:
    ports:
    - protocol: TCP
      port: 27017
      targetPort: 9376
    # clusterIP: None
    type: NodePort
    selector:
      role: mongo
---