---
apiVersion: v1
kind: Service
metadata:
    name: zk-svc
    labels:
    name: zk-svc
spec:
    ports:
    - name: server
      port: 2888
      targetPort: 2888
    - name: leader-election
      port: 3888
      targetPort: 3888
    clusterIP: None
    selector:
      app: zk-svc
---